komonjo:
  image: hkdnet/komonjo
  environment:
    - RACK_ENV=development
    - KOMONJO_DEBUG=$KOMONJO_DEBUG
    - KOMONJO_SLACK_API_TOKEN=$KOMONJO_SLACK_API_TOKEN
  command: rackup -p 80 -o 0.0.0.0
