komonjo:
  image: hkdnet/komonjo
  ports:
    - 8000:8000
  environment:
    - RACK_ENV=development
    - KOMONJO_DEBUG=$KOMONJO_DEBUG
    - KOMONJO_SLACK_API_TOKEN=$KOMONJO_SLACK_API_TOKEN
  command: rackup -p 8000 -o 0.0.0.0
